### ISSUE TITLE
always fails

### ISSUE THREAD

**Issue by realdaveblanch** [Ort0x36/Dimorf#2]
Traceback (most recent call last):
  File "/home/horseCock/Dimorf/./dimorf.py", line 18, in <module>
    def check_os(osname: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Ort0x36** [comment]
I'm sorry, it was my mistake. This error is due to the use of the "type annotation arrow", it is used to indicate the type of data that the function returns, the Dimorf code uses the updated implementation of the type annotation arrow released for python 3.10x, which it means that with in this version I use multiple return types after the arrow, python versions prior to python3.10x do not support this type of syntax. But I implemented the fix for this bug by defaulting to just a return type after the arrow and now it should work as expected. Thank you for the warning.
